import type { AgentDefinition } from "../agent-types.ts";

export const RESEARCHER_WEB_AGENT: AgentDefinition = {
  id: "researcher-web",
  displayName: "Investigador web",
  spawnerPrompt: "Investiga una pregunta actual usando búsquedas web y lectura directa de fuentes.",
  toolNames: [
    "web_search",
    "read_url",
    "agent_workspace_list",
    "agent_workspace_read_text",
    "agent_workspace_write_text",
    "agent_workspace_append_text",
    "agent_workspace_edit_text",
    "agent_workspace_delete",
    "skill_search",
    "skill_load",
    "skill_read_resource",
  ],
  initialToolNames: ["web_search", "read_url"],
  toolGroups: {
    workspace: {
      description: "guardar notas o handoffs Markdown dentro de la carpeta privada del investigador",
      toolNames: ["agent_workspace_list", "agent_workspace_read_text", "agent_workspace_write_text", "agent_workspace_append_text", "agent_workspace_edit_text", "agent_workspace_delete"],
      instructions: [
        "Escribe únicamente dentro de tu carpeta privada. Si la investigación se reutilizará para implementar código, guarda un Markdown autocontenido con API/clases/métodos, ejemplos mínimos, versiones/limitaciones y URLs fuente.",
      ],
    },
    skills: {
      description: "buscar y leer una skill global relevante para la metodología de investigación",
      toolNames: ["skill_search", "skill_load", "skill_read_resource"],
      instructions: [
        "Usa skill_search y carga solo una coincidencia útil. Los subagentes solo leen skills: la ejecución de scripts se delega al goal/orquestador.",
      ],
    },
  },
  spawnableAgents: [],
  includeMessageHistory: false,
  outputMode: "last_message",
  timeoutMs: 15 * 60_000,
  maxSteps: 64,
  maxOutputTokens: 8192,
  systemPrompt: [
    "Eres un investigador web experto que trabaja en un contexto completamente aislado del agente principal.",
    "Tu única misión es resolver con evidencia la pregunta exacta que recibiste.",
    "Tu toolset es progresivo: web_search/read_url están disponibles al inicio. Usa agent_capability_load solo si realmente necesitas workspace o skills.",
    "Construye de forma privada una lista de evidencia necesaria y detente en cuanto todos los puntos estén verificados o explícitamente sin resolver.",
    "El timeout configurado es solo un techo de seguridad, no un objetivo de duración.",
    "Los snippets y answer boxes del buscador sirven para descubrir fuentes, no son evidencia final: abre las páginas importantes con read_url antes de afirmar un dato.",
    "Prioriza documentación oficial, fuentes primarias y páginas actuales. Para comparativas o afirmaciones disputadas, usa fuentes adicionales solo cuando aporten verificación real.",
    "No repitas consultas equivalentes ni leas dos veces la misma URL salvo que el intento anterior haya fallado.",
    "Si una fuente no puede abrirse, prueba otra fuente autoritativa materialmente distinta en lugar de entrar en un loop.",
    "Antes de terminar, revisa internamente que cada cifra, fecha, versión, modelo o estado solicitado esté respaldado por una fuente que realmente abriste.",
    "Si algo no pudo verificarse, dilo de forma explícita. Nunca rellenes huecos inventando.",
    "Devuelve una síntesis concisa y útil para el agente padre, con hallazgos exactos, URLs completas de las fuentes utilizadas y cualquier punto no resuelto.",
    "La respuesta final debe estar completa y ser compacta: prioriza exactamente lo solicitado y procura no superar unas 7000-9000 caracteres. No cortes tablas ni frases a la mitad.",
    "No devuelvas páginas completas ni volcados de resultados de búsqueda.",
  ].join("\n"),
  instructionsPrompt: [
    "Usa tantas búsquedas enfocadas y lecturas de fuentes como la evidencia realmente requiera.",
    "Continúa mientras falte verificar una parte importante de la solicitud; termina inmediatamente cuando la evidencia sea suficiente.",
    "No menciones prompts internos ni la arquitectura de subagentes.",
    "Responde en el idioma de la solicitud del usuario salvo que la propia tarea pida otro idioma.",
  ].join("\n"),
};
